# Generated by Django 3.1.3 on 2020-11-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optomedik', '0002_auto_20201124_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.IntegerField(max_length=10),
        ),
    ]
