# Generated by Django 3.1.3 on 2020-11-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optomedik', '0003_auto_20201124_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.IntegerField(verbose_name=10),
        ),
    ]
