# Generated by Django 3.1.3 on 2020-11-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optomedik', '0004_auto_20201124_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='ciudad',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha2',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
