# Generated by Django 3.1.3 on 2020-11-24 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('optomedik', '0005_auto_20201124_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='fecha2',
        ),
        migrations.CreateModel(
            name='turnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True)),
                ('id_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_medico', to='optomedik.medico')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_paciente', to='optomedik.paciente')),
            ],
        ),
    ]
