# Generated by Django 3.1.3 on 2020-12-01 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optomedik', '0011_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='bio',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='company',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='url',
        ),
    ]
