# Generated by Django 3.1.3 on 2020-12-01 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('optomedik', '0014_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='id_perfil',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='fk_perfil', to='optomedik.perfil'),
            preserve_default=False,
        ),
    ]
