# Generated by Django 3.1.3 on 2020-12-01 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optomedik', '0015_userprofile_id_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='descripcion',
        ),
    ]
