# Generated by Django 3.1.3 on 2020-12-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optomedik', '0016_remove_userprofile_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='tipo_perfil',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
