# Generated by Django 3.1.3 on 2020-12-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optomedik', '0018_remove_perfil_tipo_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='tipo_perfil',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
