# Generated by Django 3.1.3 on 2020-12-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optomedik', '0020_remove_perfil_tipo_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('compiled', models.BooleanField(default=False, help_text='Compiled or interpreted')),
                ('learned_at', models.DateField(blank=True, help_text='When you learned the language', null=True)),
                ('observations', models.TextField(blank=True, max_length=500)),
                ('main_paradigm', models.CharField(choices=[('procedural', 'Procedural'), ('declarative', 'Declarative'), ('functional', 'Functional'), ('OOP', 'Object Oriented')], default='procedural', max_length=20)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
    ]
