# Generated by Django 3.1.3 on 2020-12-01 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optomedik', '0021_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'registro', 'verbose_name_plural': 'optomedik'},
        ),
    ]
