# Generated by Django 3.1.3 on 2020-12-02 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('optomedik', '0022_auto_20201201_1846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turnos',
            options={'verbose_name': 'registro', 'verbose_name_plural': 'optomedik'},
        ),
        migrations.AlterField(
            model_name='turnos',
            name='id_paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='optomedik.paciente'),
        ),
    ]
