# Generated by Django 3.1.3 on 2020-12-02 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('optomedik', '0023_auto_20201202_0023'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.AlterModelOptions(
            name='historia_clinica',
            options={'verbose_name': 'registro', 'verbose_name_plural': 'optomedik'},
        ),
        migrations.AlterField(
            model_name='turnos',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_paciente', to='optomedik.paciente'),
        ),
    ]
