# Generated by Django 3.1.3 on 2020-12-02 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optomedik', '0024_auto_20201202_1120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historia_clinica',
            options={'verbose_name': 'registrohc', 'verbose_name_plural': 'optomedik'},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'verbose_name': 'registrop', 'verbose_name_plural': 'optomedik'},
        ),
    ]
