# Generated by Django 3.1.3 on 2020-12-03 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optomedik', '0028_auto_20201202_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='user',
        ),
    ]
