# Generated by Django 3.1.3 on 2020-12-03 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optomedik', '0031_auto_20201202_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
