# Generated by Django 3.1.3 on 2020-12-03 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optomedik', '0033_remove_pedido_valor_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='lente',
            field=models.CharField(choices=[('LEJOS/IZQUIERDA', 'LEJOS/IZQUIERDA'), ('LEJOS/DERECHA', 'LEJOS/DERECHA'), ('CERCA/IZQUIERDA', 'CERCA/IZQUIERDA'), ('CERCA/DERECHA', 'CERCA/DERECHA')], default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='armazon',
            field=models.BooleanField(default=False, help_text='SI or NO'),
        ),
    ]
