# Generated by Django 3.1.3 on 2020-12-03 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optomedik', '0034_auto_20201202_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='id_clasificacion',
        ),
        migrations.AlterField(
            model_name='producto',
            name='lente',
            field=models.CharField(choices=[('NO ES LENTE', 'NO ES LENTE'), ('LEJOS/IZQUIERDA', 'LEJOS/IZQUIERDA'), ('LEJOS/DERECHA', 'LEJOS/DERECHA'), ('CERCA/IZQUIERDA', 'CERCA/IZQUIERDA'), ('CERCA/DERECHA', 'CERCA/DERECHA')], default='NO ES LENTE', max_length=20),
        ),
        migrations.DeleteModel(
            name='clasificacion',
        ),
    ]
