# Generated by Django 3.1.3 on 2020-12-03 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optomedik', '0035_auto_20201202_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='armazon',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=20),
        ),
    ]
