# Generated by Django 3.1.3 on 2020-12-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optomedik', '0036_auto_20201202_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('PEDIDO', 'PEDIDO'), ('TALLER', 'TALLER'), ('FINALIZADO', 'FINALIZADO')], default='PENDIENTE', max_length=20),
        ),
    ]
