# Generated by Django 3.1.3 on 2020-12-03 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optomedik', '0037_auto_20201203_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnos',
            name='asistio',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='SI', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PEDIDO', 'PEDIDO'), ('TALLER', 'TALLER'), ('FINALIZADO', 'FINALIZADO')], default='PEDIDO', max_length=20),
        ),
    ]
