# Generated by Django 3.1.3 on 2020-12-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optomedik', '0039_auto_20201203_0121'),
    ]

    operations = [
        migrations.CreateModel(
            name='vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
            ],
        ),
    ]
